# Generated by Django 6.0.4 on 2026-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('estatus', models.CharField(default=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('empresa', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
    ]
