# Generated by Django 6.0.4 on 2026-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
