# Generated by Django 6.0.4 on 2026-05-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='contrasena',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
            ],
        ),
    ]
