# Generated by Django 6.0.4 on 2026-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_encargo_pedido_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
